### ISSUE TITLE
Recent start.sh issues

### ISSUE THREAD

**Issue by royzawadzki** [vsoch/forward#24] opened 2018-08-23 17:00 UTC
As of lately, when I run `start.sh` it starts up as normal then gives me the following output:
```bash
== Waiting for job to start, using exponential backoff ==
Attempt 0: not ready yet... retrying in 1..
Attempt 1: not ready yet... retrying in 2..
Attempt 2: resources allocated to sh-28-06!..
sh-28-06
sh-28-06
notebook running on sh-28-06

== Setting up port forwarding ==
ssh -L 56432:localhost:56432 sherlock ssh -L 56432:localhost:56432 -N sh-28-06 &
mux_client_forward: forwarding request failed: Port forwarding failed
muxclient: master forward request failed
rzawadzk@sh-ln05.stanford.edu's password: == Connecting to notebook ==
# automatically continues which doesn't allow me to input my password


== View logs in separate terminal ==
ssh sherlock cat /home/users/rzawadzk/forward-util/py3-jupyter.sbatch.out
ssh sherlock cat /home/users/rzawadzk/forward-util/py3-jupyter.sbatch.err

== Instructions ==
1. Password, output, and error printed to this terminal? Look at logs (see instruction above)
2. Browser: http://sh-02-21.int:56432/ -> http://localhost:56432/...
3. To end session: bash end.sh sherlock/py3-jupyter

DN525eol:forward royzawadzki$ Permission denied, please try again.
rzawadzk@sh-ln05.stanford.edu's password: 
# automatically continues which doesn't allow me to input my password
Permission denied, please try again.
rzawadzk@sh-ln05.stanford.edu's password: 
# automatically continues which doesn't allow me to input my password
rzawadzk@sh-ln05.stanford.edu: Permission denied (gssapi-with-mic,password).
```

At the moment, when I get to this message and I try refreshing the link in the browser, the link is dead. If I run `resume.sh` however, the webpage becomes active.

**Comment by vsoch** [comment] 2018-08-23 18:05
I think the issue is with your password? Try closing that terminal and opening a new one, and then end.sh to the job and do start.sh again and make sure it prompts you. Also for sanity check you can try just “ssh  sherlock” to test it out. If that fails, then try logging in directly to sherlock or a different login node all together (its saved in your ssh config file).

**Comment by royzawadzki** [comment] 2018-10-29 03:00
Yes! I haven't used Sherlock in a while so I totally forgot to follow up.

**Comment by vsoch** [comment] 2018-10-29 03:01
haha no worries! I'm going to close the issue then, and please let me know if I can help if you decide to come back :)

**Closed as completed by vsoch** 2018-10-29 03:01 UTC
